spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/logate_academy
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false # Recommended value
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  ssl:
    bundle:
      jks:
        springbootssl:
          key:
            alias: springbootssl
          keystore:
            location: classpath:springbootssl.p12
            password: password
            type: PKCS12


logging:
  level:
    ROOT: TRACE
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE


# keytool -genkeypair -alias springbootssl -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore springbootssl.p12 -validity 3650
server:
  ssl:
    bundle: "springbootssl"
    enabled-protocols: TLSv1.3
  port: 8443

jwt:
  secret: ZMvXyNKUp05KkbQtDz+BrSirKl5Cg8XNILGmcgQxYrA=