spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/logate_academy
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE